Добавить парсер новостей
egormanga/StankinBot pull request #19
Opened 2021-09-30 19:16 UTC by BasedUser

2021-09-30 19:18 UTC, egormanga commented on modules/backend/stankin_api.py
> +		if(art.get('short_text') != ""):
```python3
if (art.get('short_text')):
```

2021-09-30 19:22 UTC, egormanga requested changes

2021-09-30 19:22 UTC, egormanga commented on modules/backend/stankin_api.py
> +import re
```python3
import re, time, aiohttp
```

2021-09-30 19:22 UTC, egormanga commented on modules/backend/stankin_api.py
> +
лишняя

2021-09-30 19:22 UTC, egormanga commented on modules/backend/stankin_api.py
> +	base_url = "https://stankin.ru" # note: no trailing /
Два пробела:
```python3
"  #
```

2021-09-30 19:22 UTC, egormanga commented on modules/backend/stankin_api.py
> +			output += "\n\n" + art.get('short_text')
```python3
if (short_text := art.get('short_text')):
	output += '\n\n' + short_text
```

2021-09-30 19:22 UTC, egormanga commented on modules/backend/stankin_api.py
> +	async def parseNewsArticle(art): # returns str of plaintext-ready message
Два пробела:
```python3
:  #
```

2021-09-30 19:26 UTC, egormanga requested changes

2021-09-30 19:26 UTC, egormanga commented on modules/backend/stankin_api.py
> +		output += art.get('title') + "\n\n" + "https://stankin.ru/news/item_" + str(art.get('id'))
```python3
`\n\n`
```

2021-09-30 19:26 UTC, egormanga commented on modules/backend/stankin_api.py
> +			output = re.sub(r'( 00:00:\d\d)|( 23:59:\d\d)','',time.strftime("%c",time.strptime(re.sub(r'\.\d+', '', art.get('date') + "00"), '%Y-%m-%d %H:%M:%S%z'))) + "\n"
Пробел после запятой:
```python3
', '
```

2021-09-30 19:32 UTC, BasedUser commented on modules/backend/stankin_api.py
> +		output += art.get('title') + "\n\n" + "https://stankin.ru/news/item_" + str(art.get('id'))
Оставляю, т.к. входит в часть данных.

2021-09-30 22:09 UTC, egormanga commented on modules/backend/stankin_api.py
> +		output += art.get('title') + "\n\n" + "https://stankin.ru/news/item_" + str(art.get('id'))
Тогда не надо было вообще отделять, т.е. `"\n\nhttps://"`.

2021-09-30 22:14 UTC, egormanga requested changes

2021-09-30 22:14 UTC, egormanga commented on modules/backend/stankin_api.py
> +			output = re.sub(r'( 00:00:\d\d)|( 23:59:\d\d)', '', time.strftime("%c", time.strptime(re.sub(r'\.\d+', '', art.get('date') + "00"), '%Y-%m-%d %H:%M:%S%z'))) + "\n"
```python3
r'\ (00:00|23:59):\d{2}'
```

2021-09-30 22:14 UTC, egormanga commented on modules/backend/stankin_api.py
> +		output += art.get('title') + "\n\n" + "https://stankin.ru/news/item_" + str(art.get('id'))
Тогда не надо было вообще отделять, т.е. `"\n\nhttps://"`.

2021-09-30 22:14 UTC, egormanga commented on modules/backend/stankin_api.py
> +
лишняя

2021-09-30 22:14 UTC, egormanga commented on modules/backend/stankin_api.py
> +	async def parseNewsArticle(art):  # returns str of plaintext-ready message
```python3
parseNewsArticle(art) -> plaintext[str]:
```

2021-09-30 22:14 UTC, egormanga commented on modules/backend/stankin_api.py
> +# by Sdore and BasedUser, 2021
`s/and/\&/`

2021-10-03 22:41 UTC, egormanga approved these changes

2021-10-03 22:44 UTC, merged